# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install OpenAPI Tools
      run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1

    - name: Install Mockery
      run: go install github.com/vektra/mockery/v2@v2.46.3

    - name: Download Mods
      run: go mod tidy

    - name: Generate Code
      run: go generate -v ./...

    - name: Test Code
      run: go test -v ./...
