# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Install dependencies
      run: go mod download

    - name: Install OpenAPI Tools
      run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1

    - name: Install sysbox-run docker host runtime
      run:
        # Docs: https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md#installing-sysbox
        cd /tmp
        wget https://downloads.nestybox.com/sysbox/releases/v0.6.7/sysbox-ce_0.6.7-0.linux_amd64.deb
        sudo apt-get install ./sysbox-ce_0.6.7-0.linux_amd64.deb -y

    - name: Download Mods
      run: go mod tidy

    - name: Generate mockery mocks
      run: go tool mockery

    - name: Generate Code
      run: go generate -v ./...

    - name: Test Code
      run: go test -v ./...
      env:
        EXECUTOR_END_TO_END_TESTS: true
        TEST_DOCKER_EXECUTOR_SOCKET_PATH: /var/run/docker.sock

