/*
 * Tyk Gateway API
 *
 * The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>
 *
 * API version: 5.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExtendedPathsSet struct {
	AdvanceCacheConfig []CacheMeta `json:"advance_cache_config,omitempty"`
	BlackList []EndPointMeta `json:"black_list,omitempty"`
	Cache []string `json:"cache,omitempty"`
	CircuitBreakers []CircuitBreakerMeta `json:"circuit_breakers,omitempty"`
	DoNotTrackEndpoints []TrackEndpointMeta `json:"do_not_track_endpoints,omitempty"`
	HardTimeouts []HardTimeoutMeta `json:"hard_timeouts,omitempty"`
	Ignored []EndPointMeta `json:"ignored,omitempty"`
	Internal []InternalMeta `json:"internal,omitempty"`
	MethodTransforms []MethodTransformMeta `json:"method_transforms,omitempty"`
	RateLimit []RateLimitMeta `json:"rate_limit,omitempty"`
	SizeLimits []RequestSizeMeta `json:"size_limits,omitempty"`
	TrackEndpoints []TrackEndpointMeta `json:"track_endpoints,omitempty"`
	Transform []TemplateMeta `json:"transform,omitempty"`
	TransformHeaders []HeaderInjectionMeta `json:"transform_headers,omitempty"`
	TransformJq []TransformJqMeta `json:"transform_jq,omitempty"`
	TransformJqResponse []TransformJqMeta `json:"transform_jq_response,omitempty"`
	TransformResponse []TemplateMeta `json:"transform_response,omitempty"`
	TransformResponseHeaders []HeaderInjectionMeta `json:"transform_response_headers,omitempty"`
	UrlRewrites []UrlRewriteMeta `json:"url_rewrites,omitempty"`
	ValidateJson []ValidatePathMeta `json:"validate_json,omitempty"`
	Virtual []VirtualMeta `json:"virtual,omitempty"`
	WhiteList []EndPointMeta `json:"white_list,omitempty"`
}
